name: Build Windows

on: [push]

jobs:
  windows:
    name: Build & Test (${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x64
            runner: windows-2022
            qt_arch: win64_msvc2022_64
            qt_dir: msvc2022_64
            cmake_arch: x64
            system_version: 10.0.20348.0
          - target: arm64
            runner: windows-11-arm
            qt_arch: win64_msvc2022_arm64
            qt_dir: msvc2022_arm64
            cmake_arch: ARM64
            system_version: 10.0.22621.0
    runs-on: ${{ matrix.runner }}
    env:
      PLATFORM: ${{ matrix.target }}
      WIRESHARK_BASE_DIR: C:\Development
      CMAKE_PREFIX_PATH: ${{ github.workspace }}\..\Qt\6.8.3\${{ matrix.qt_dir }}
      WIRESHARK_VERSION_EXTRA: -GithubActionBuild
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Choco install
        run: choco install -y --force --no-progress xsltproc nsis winflexbison3 cmake
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          dir: ${{ github.workspace }}\..
          arch: ${{ matrix.qt_arch }}
          version: 6.8.3
          modules: 'qt5compat'
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v3
        with:
          vs-version: '[17.0,18.0)'
      - name: Set MSVC command prompt
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: ${{ matrix.target }}
      - name: Mkdir
        run: mkdir build
      - name: Cmake
        run: cmake -DCMAKE_SYSTEM_VERSION="${{ matrix.system_version }}" -A ${{ matrix.cmake_arch }} ..
        env:
          PLATFORM: ${{ matrix.target }}
          WIRESHARK_BASE_DIR: C:/wireshark-libs
        working-directory: build
      - name: Build
        run: cmake --build . --config RelWithDebInfo
        working-directory: build
      - name: Build guides
        run: cmake --build . --config RelWithDebInfo --target user_guide_html
        working-directory: build
      - name: Build test-programs
        run: cmake --build . --config RelWithDebInfo --target test-programs
        working-directory: build
      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Install pytest
        run: pip install pytest pytest-xdist
      - name: Run tests
        run: pytest
        working-directory: build
      - name: Build Windows pkg
        run: |
          msbuild /m /p:Configuration=RelWithDebInfo wireshark_nsis_prep.vcxproj
          msbuild /m /p:Configuration=RelWithDebInfo wireshark_nsis.vcxproj
        working-directory: build
      - name: Upload Windows packages
        uses: actions/upload-artifact@v6
        with:
          name: package-${{ matrix.target }}
          path: build/packaging/nsis/*exe
